name: house-votes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # optional daily run

jobs:
  scrape-votes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install fast-xml-parser node-fetch

      - name: Run Clerk XML vote scraper
        run: node scripts/votes-reps-scraper.js

      - name: Commit updated vote file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add public/representatives-votes.json
          git commit -m "Update House votes" || echo "No changes"
          git push
